my_app_messagerie_index:
    path: /user/
    defaults: { _controller: MyAppMessagerieBundle:Utilisateur:index }

my_app_messagerie_ajouter:
    path: /user/ajouter/
    defaults: { _controller: MyAppMessagerieBundle:Utilisateur:ajouter }

my_app_messagerie_connecter:
    path: /user/connecter/
    defaults: { _controller: MyAppMessagerieBundle:Utilisateur:connecter }

my_app_messagerie_envoyer:
    path: /user/{id}/envoyer/
    defaults: { _controller: MyAppMessagerieBundle:Utilisateur:envoyer }

my_app_messagerie_listerenvoyes:
    path: /user/{id}/listerenvoyes/
    defaults: { _controller: MyAppMessagerieBundle:Utilisateur:listermessagesenvoyes }

my_app_messagerie_listerrecus:
    path: /user/{id}/listerrecus/
    defaults: { _controller: MyAppMessagerieBundle:Utilisateur:listermessagesrecus }

my_app_messagerie_download:
    path: /user/{id}/listerenvoyes/download/{path}/
    defaults: { _controller: MyAppMessagerieBundle:Utilisateur:download }